--- 
name: Build and Deploy NP Labs Website to Cloudfront

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
      env:
        BUCKET_NAME: site.np-labs.org
        DIST: build
        REGION: us-east-2
        DIST_ID: E3USJRUQN0MVNO

      steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS Credentials 
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.REGION }}

      - name: Install dependencies
        run: |
          node --version
          npm ci --production

      - name: Build Static Website
        run: npm run build

      - name: Copy files to the production website with the AWS CLI
        run: |
          aws s3 cp --delete ${{ env.DIST }} s3://${{ env.BUCKET_NAME }}

      - name: Invalidate Cloudfront Distribution
        run: |
          aws cloudfront create-invalidation \
          --distribution-id ${{ env.DIST_ID }} \
          --paths "/*"
        
        
        